resources:
- name: sonar-scanner-source
  type: git
  source: 
    uri: https://github.com/emerald-squad/sonar-scanner.git
    branch: 'master'

- name: docker-hub-version
  type: docker-image
  source:
    repository: emeraldsquad/sonar-scanner-test
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: "1.0.4"


- name: docker-hub-latest
  type: docker-image
  source:
    repository: emeraldsquad/sonar-scanner-test
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:
- name: publish
  plan:
  - aggregate:
    - get: sonar-scanner-source
  - put: docker-hub-version
    params:
      build: sonar-scanner-source
      tag_as_latest: false

- name: tag-as-latest
  plan:
  - aggregate:
    - get: sonar-scanner-source
      passed: [ publish ]
    - get: docker-hub-version
      params:
        save: true
  - put: docker-hub-latest
    params:
      load: docker-hub-version

